### ISSUE TITLE
Handleing diffrent type of rows

### ISSUE THREAD

**Issue by nekofar** [kanytu/android-parallax-recyclerview#10]
As I noticed you are overriding **getItemViewType** method. I wanted to know if you have suggestion for handling different type the rows.

**Comment by kanytu** [comment]
You just have to change `return position == 0 ? VIEW_TYPES.HEADER : VIEW_TYPES.NORMAL;` to return your own viewtype if it's not position = 0. The only restriction is that the first view shouldn't be of type `VIEW_TYPES.FIRST_VIEW` because of screen orientation issues. Other than that you are free to change your viewtype implementation: 

Example
=======


    @Override
    public int getItemViewType(int position) {
        if (mRecyclerAdapterMethods == null)
            throw new NullPointerException("You must call implementRecyclerAdapterMethods");
        if (position == 1)
            return VIEW_TYPES.FIRST_VIEW;
        if(position==0)
              return VIEW_TYPES.HEADER;
        if (position%2 ==0)
              return VIEW_TYPES.TYPE1;
        return VIEW_TYPES.TYPE2;
    }

**Comment by foolchen** [comment]
@nekofar #14
