### ISSUE TITLE
How I can use your adapter with dynamic data

### ISSUE THREAD

**Issue by slidenerd** [kanytu/android-parallax-recyclerview#11]
I am trying to create an instance of your adapter by extending it to load arraylist of custom objects from the internet, initially it ll have nothing but later it ll be filled with data.
![snap 2015-02-27 at 10 03 01](https://cloud.githubusercontent.com/assets/5139030/6407530/f6b902e6-be67-11e4-8d5f-27eabbfc57f6.png)
I get this error saying 'no default constructor available' what would be the optimal way to load nothing initially and then load data inside the parallax from the internet, thanks for your reply in advance

**Comment by kanytu** [comment]
Hello.

Yes you can use an adapter with dynamic data. Any one of the, not just mine. And the progress to do it is the same in any adapter.

To start you should override the constructor I'm currently using:

`public ParallaxRecyclerAdapter(List<T> data)`

You can use your custom constructor but you MUST call `super.ParallaxRecyclerAdapter(List<T>);`. In this case you have no list on your constroctor because you want to fech the data later. But in this case you can simply pass an empty `ArrayList<Group>` to the parent class. I don't have access to your code for an easy paste but it should look like this:

	public ParallaxAdapterGroups(Context context){
	super(new ArrayList<Group>);
	this.mContext = context;
	(...)
	}

Now when you start your app your list will be empty only with the header. It's time to fetch your data from the internet. Do this wherever you want. The point is to update the `mListGroups` on your adapter and send it back to the `ParallaxRecyclerAdapter.` You can update the content of the adapter by calling `ParallaxRecyclerAdapter.setData(List<T> data)`. However, and because you implemented your `RecyclerAdapterMethods` you might have to check if you're really returning mListGroups.size on `getItemCount`.

Here is an example of an adapter with dynamic data just for you :)


https://gist.github.com/kanytu/c71501b16ebd9bec4b43

**Comment by slidenerd** [comment]
Thank you very much kanytu, I ll try this out inside my navigation drawer and let you know, if everything s good I ll close the issue :)

**Comment by kanytu** [comment]
Did you managed to solve your problem @slidenerd ?

**Comment by hongzhou85** [comment]
I tried this method and it works good so far :)
