### ISSUE TITLE
ScrollToPosition make the header dissapear

### ISSUE THREAD

**Issue by cgomezmendez** [kanytu/android-parallax-recyclerview#18]
when I do scroll with my fingers everything works fine, but if I want to do it programmatic and for example go to the last element with something like:

<pre>
recyclerview.scrollToPosition(adapter.getItemCount()-1);
</pre>

it doesn't work, even with the sample code on this repo, it scrolls but header dissapear when i scroll up again to the same place.

**Comment by kooze** [comment]
I have the same issue with you.

**Comment by kanytu** [comment]
Hi..

Sorry for the time I took to help you with this issue.

Could you try recyclerView.getLayoutManager().smoothScrollToPosition instead?

**Comment by kooze** [comment]
SmoothScrollToPosition() has no such issue both on recyclerView or recyclerView.getLayoutManager() object. But ScrollToPosition() has such issue on both of them.

Well, it looks like that ScrollToPosition() also push the parallax header the same distance as the recyclerView items. For example in the screenshot:

![device-2015-06-06-164653](https://cloud.githubusercontent.com/assets/4645158/8019062/c8a55d38-0c6d-11e5-98a0-5e83db20361e.png)
![device-2015-06-06-165158](https://cloud.githubusercontent.com/assets/4645158/8019063/c9231ad4-0c6d-11e5-8e48-8fb91b331b47.png)
![device-2015-06-06-165839](https://cloud.githubusercontent.com/assets/4645158/8019064/c973fed6-0c6d-11e5-95e1-d7f5616622af.png)

As you can see. I scroll the recyclerView for a half of the parallax header height. And the ScrollToPosition(0). It shows the last pic.

**Comment by kanytu** [comment]
But didnt you solved your problem by changing to smoothscroll? Because the problem is that scrolltoposotion  doesn't call onSroll. That's why you get that effect

**Comment by kooze** [comment]
@kanytu Yes, smooth scroll do resolve this problem. But in some situation, for example, long recyclerView, smooth scroll need wait for a relatively long time. So, it need scrollToPosition().

So, is it possible that scrollToPosition() method go well in parallax-recyclerView?

Thank you for your reply, @kanytu .

**Comment by kanytu** [comment]
@kooze  I will need you to override LinearLayoutManager to change the method for smoothScrollToPosition. The problem here is that scroolToPosition doesn't call the listener onScroll which is responsible to change the view offset.

http://stackoverflow.com/a/28853254/3410697

Here you can find an explanation of how to change the speed of smoothScrollToPosition. The first solution should be the best one. The calculateSpeedPerPixel is controls the speed of the scroll animation. With some tweaks you should be able to mimify the same effect of scrollToPosition()

Good luck :)

**Comment by SaravanaWorkspaces** [comment]
Hi Kanytu i used your library but my header view gets padding unfortunately. I just checked eveything from my end all fine. even i made a test programs. thats works fine. but in my project i dont know what gone wrong. instead of using normal adapter and all works fine..

![device-2015-06-27-152622](https://cloud.githubusercontent.com/assets/4908474/8391489/0c50ceb6-1ce3-11e5-9f64-ab08a4528590.png)
